basket = ["Banana", "Apples", "Oranges", "Blueberries"];
print(basket)
basket.remove("Banana")
print(basket)
basket.remove("Blueberries")
print(basket)
basket.append("Kiwi")
print(basket)
basket.append("Apples")
print(basket)
print(basket.count("Apples"))
basket.clear()
print(basket)